### ISSUE TITLE
Search / Timeline dates are not linear

### ISSUE THREAD

**Issue by gerard070** [project-seldon/intake#37]
![image](https://user-images.githubusercontent.com/20401390/221428226-b6647651-f338-4b7e-b6ac-5e5725435652.png)

Timeline dates are not displayed as expected. In The screenshot example, the events are presented in this order;

 1944, 2019, 2013

This is a problem universal

**Comment by skipjack** [comment]
☝️ @gerard070 remember you don't need to capitalize everything in the issue titles. Just the section of the application and then the first letter of the concise sentence describing the idea or problem. Otherwise this title was perfect! Also I'll take a look at your PR today, thanks for putting that together 🙏
